function [interp_fun, gof] = createinterp(angles, sens)
%CREATEFIT(ANGLES,SENS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: angles
%      Y Output: sens
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Aug-2024 10:59:09


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( angles, sens );

% Set up fittype and options.
ft = 'cubicinterp';
opts = fitoptions( 'Method', 'CubicSplineInterpolant' );
opts.ExtrapolationMethod = 'cubic';
opts.Normalize = 'on';

% Fit model to data.
[interp_fun, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( interp_fun, xData, yData );
% legend( h, 'sens vs. angles', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'angles', 'Interpreter', 'none' );
% ylabel( 'sens', 'Interpreter', 'none' );
% grid on


save('interp_fun.mat', 'interp_fun');



